const constants = {
    CHARACTER: 'CHARACTER',
    CHARACTERS: 'CHARACTERS',
    CHARACTER_CURRENT: 'CHARACTER_CURRENT',
    REQUEST_CHARACTER: 'REQUEST_CHARACTER',
    REQUEST_CHARACTER_CURRENT: 'REQUEST_CHARACTER_CURRENT',
    REQUEST_CHARACTERS: 'REQUEST_CHARACTERS',
    STATS: 'STATS',
    REQUEST_STATS: 'REQUEST_STATS',
    GIVE_CARROT: 'GIVE_CARROT'
}

export default constants;